# Generated by Django 5.2.5 on 2025-08-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('planoDeContas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaccount',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_contas', to='empresa.empresa'),
        ),
    ]
