# Generated by Django 5.2.5 on 2025-08-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia/Alias')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('matriz', models.BooleanField(default=False, verbose_name='É Matriz')),
                ('status', models.CharField(max_length=100, verbose_name='Status da Empresa')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social')),
                ('atividade_principal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atividade Principal')),
                ('atividades_secundarias', models.TextField(blank=True, null=True, verbose_name='Atividades Secundárias')),
                ('porte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte da Empresa')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Rua/Avenida')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('pais', models.CharField(max_length=255, verbose_name='País')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empresa ou Pessoa Física',
                'verbose_name_plural': 'Empresas e Pessoas Físicas',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('principal', models.BooleanField(default=False, verbose_name='Atividade Principal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Atividade Econômica',
                'verbose_name_plural': 'Atividades Econômicas',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Sócio')),
                ('cpf', models.CharField(max_length=18, verbose_name='CPF do Sócio')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função/Cargo')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('faixa_etaria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Faixa Etária')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sócio',
                'verbose_name_plural': 'Sócios',
            },
        ),
    ]
